apiVersion: skaffold/v1beta2
kind: Config 
build:
  local:
    push: false
  artifacts:
    - image: volvo745rules/multi-client
      context: client  
      docker:
        dockerfile: Dockerfile.dev 
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
